### ISSUE TITLE
web-ui

### ISSUE THREAD

**Issue by jhbpxx-king** [wangduanduan/siphub#1]
辛苦问下这个siphub-ui的代码在哪里哈？想了解下这块啊。

**Comment by wangduanduan** [comment]
这块其实也是比较简单的，从数据库中查处相同CallID的数据后，用https://github.com/bramp/js-sequence-diagrams 绘制的流程图。

本身hep协议的格式就非常合适来绘制时序图。

**Comment by zhaoqunshuai** [comment]
这部分的代码能否也开源呢？
非常感谢
